<a href="https://colab.research.google.com/github/suprit-chafle/BranchRepository/blob/master/eigenValuEandEigenVector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A=np.array([[2,-2,3],[1,1,1],[1,3,-1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [5]:
B=np.array([[2,0,0],[0,1,0],[0,0,-1]])
print(B)


[[ 2  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [6]:
val,vect=np.linalg.eig(B)
print(val)
print(vect)

[ 2.  1. -1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
values,vector=np.linalg.eig(A)
print(values)
print(vector)

[ 3.  1. -2.]
[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]
